### ISSUE TITLE
AttributeError: 'HParams' object has no attribute 'modality'

### ISSUE THREAD

**Issue by artabc** [MostafaDehghani/bAbI-T2T#6]
I’m just trying to run the example in the readme but it’s giving the error. How can we fix that? Thank you. 

```
t2t-trainer \
  --t2t_usr_dir=~/bAbI-T2T/t2t_usr_dir \
  --tmp_dir=~/babi_data/tmp \
  --data_dir=~/babi_data/data \
  --output_dir=~/babi_data/output \
  --problem=babi_qa_sentence_task1_10k \
  --model=babi_transformer \
  --hparams_set=transformer_tiny \
  --train_steps=100000
```

```
AttributeError: 'HParams' object has no attribute 'modality' 
```

**Comment by MostafaDehghani** [comment]
Oh... I see... It's because of the new changes in T2T. I'll fix it soon and will get back to you here. In the meantime, you can use older versions of T2T and use this code with no problem :)

**Comment by artabc** [comment]
Thank you for your response. I see that it works now using T2T v1.9.0. I would love to contribute to the project and fix the issue so that it works on the latest T2T. Can you offer some advice on where I can fix the issue in the code? I can then submit a pull request.

**Comment by MostafaDehghani** [comment]
Thanks @artabc for your suggestion to help with this :) 
It was actually [a quick fix](https://github.com/MostafaDehghani/bAbI-T2T/commit/45faa79d4ae748cda8f877870bed2b4c8f1a8a89) so I just did it myself! It should work now! Feel free to open the issue if you got any problem.
